# Generated by Django 5.0.3 on 2024-03-15 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_letter_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='path',
            field=models.FileField(upload_to='letter/%D', validators=[django.core.validators.FileExtensionValidator(['html'])]),
        ),
    ]
