# Generated by Django 5.0.3 on 2024-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_alter_letter_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='image',
            field=models.ImageField(default='NONE', upload_to='image/%D'),
            preserve_default=False,
        ),
    ]
