# Generated by Django 5.0.3 on 2024-03-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
    ]
